rAuthError = ("Authentication failed\n", 401)
rNotEnrolled = ("Not enrolled in service\n", 400)
rInternalServerError = ("Internal Server Error\n", 500)
rMissingParams = lambda params: ("Required Params: {}\n".format(params), 400)
rMissingServiceInfo = ("Please provide full service information\n", 400)
