rAuthError = ("Authentication failed", 401)
rNotEnrolled = ("Not enrolled in service", 400)
rInternalServerError = ("Internal Server Error", 500)
rMissingParams = lambda params: ("Required Params: {}".format(params), 400)
rMissingServiceInfo = ("Please provide full service information", 400)
